# Generated by Django 5.2 on 2025-06-24 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('type', models.CharField(choices=[('COMPANY', 'Compañía'), ('COMMAND', 'Comandancia'), ('CENTRAL', 'Central de Comunicaciones'), ('ADMIN', 'Administración General')], max_length=20, verbose_name='Tipo de entidad')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/entity_logos/', verbose_name='Logo institucional')),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
                'permissions': [('view_own_entity', 'Puede ver solo su entidad')],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('is_unique', models.BooleanField(default=False, verbose_name='Cargo exclusivo')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.permission', verbose_name='Permisos')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='MembershipHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(editable=False, max_length=100, verbose_name='Nombre completo')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de término')),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firebrigade.entity', verbose_name='Entidad')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firebrigade.position', verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Historial de cargo',
                'verbose_name_plural': 'Historial de cargo',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firebrigade.entity', verbose_name='Entidad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firebrigade.position', verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Asignación de cargo',
                'verbose_name_plural': 'Asignaciones de cargo',
            },
        ),
    ]
