# Generated by Django 5.2 on 2025-04-07 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('firebrigade', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name': 'Entidad', 'verbose_name_plural': 'Entidades'},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'Asignación de cargo', 'verbose_name_plural': 'Asignaciones de cargo'},
        ),
        migrations.AlterModelOptions(
            name='membershiphistory',
            options={'verbose_name': 'Historial de cargo', 'verbose_name_plural': 'Historial de cargo'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
        migrations.RemoveField(
            model_name='membershiphistory',
            name='user',
        ),
        migrations.AddField(
            model_name='membershiphistory',
            name='full_name',
            field=models.CharField(default='Hola Mundo', editable=False, max_length=100, verbose_name='Nombre completo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entity',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='entity_logos/', verbose_name='Logo institucional'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='type',
            field=models.CharField(choices=[('COMPANY', 'Compañía'), ('COMMAND', 'Comandancia'), ('CENTRAL', 'Central de Comunicaciones'), ('ADMIN', 'Administración General')], max_length=20, verbose_name='Tipo de entidad'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firebrigade.entity', verbose_name='Entidad'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firebrigade.position', verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='membershiphistory',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de término'),
        ),
        migrations.AlterField(
            model_name='membershiphistory',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firebrigade.entity', verbose_name='Entidad'),
        ),
        migrations.AlterField(
            model_name='membershiphistory',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firebrigade.position', verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='membershiphistory',
            name='start_date',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='position',
            name='is_unique',
            field=models.BooleanField(default=False, verbose_name='Cargo exclusivo'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='position',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.permission', verbose_name='Permisos'),
        ),
    ]
