# Generated by Django 4.2.7 on 2025-08-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firebrigade', '0002_alter_membership_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='entity_logos/', verbose_name='Logo institucional'),
        ),
    ]
