# Generated by Django 5.2 on 2025-04-09 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firebrigade', '0002_alter_entity_options_alter_membership_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/entity_logos/', verbose_name='Logo institucional'),
        ),
    ]
