# Generated by Django 5.2 on 2025-06-12 21:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documentos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx'])])),
                ('short_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FileVencible',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='docs.file')),
                ('expiration_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Archivo con vencimiento',
                'verbose_name_plural': 'Archivos con vencimiento',
            },
            bases=('docs.file',),
        ),
    ]
