# Generated by Django 5.2 on 2025-04-08 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firebrigade', '0002_alter_entity_options_alter_membership_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tipo de vehículo')),
            ],
            options={
                'verbose_name': 'Tipo de vehículo',
                'verbose_name_plural': 'Tipos de vehículos',
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('address', models.CharField(max_length=100, verbose_name='Dirección')),
                ('phone', models.CharField(max_length=12, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
            ],
            options={
                'verbose_name': 'Taller',
                'verbose_name_plural': 'Talleres',
            },
        ),
        migrations.CreateModel(
            name='MajorEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=10, unique=True, verbose_name='Número de unidad')),
                ('short_description', models.CharField(max_length=100, verbose_name='Descripción')),
                ('plate_number', models.CharField(max_length=10, unique=True, verbose_name='Placa patente')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Año')),
                ('fuel_type', models.IntegerField(blank=True, choices=[(1, 'Bencina - 93 octanos'), (2, 'Bencina - 95 octanos'), (3, 'Bencina - 97 octanos'), (4, 'Diésel'), (5, 'Eléctrico')], null=True, verbose_name='Tipo de combustible')),
                ('cylinders', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cilindros')),
                ('displacement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cilindrada')),
                ('transmission', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transmisión')),
                ('drive_system', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sistema de tracción')),
                ('fuel_tank_capacity', models.CharField(blank=True, max_length=100, null=True, verbose_name='Capacidad del estanque de combustible')),
                ('engine_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de motor')),
                ('chassis_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de chasis')),
                ('motor_oil_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de aceite de motor')),
                ('motor_oil_capacity', models.CharField(blank=True, max_length=100, null=True, verbose_name='Capacidad de aceite de motor')),
                ('gearbox_oil_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de aceite de caja de cambios')),
                ('differential_oil_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de aceite de diferencial')),
                ('differential_oil_capacity', models.CharField(blank=True, max_length=100, null=True, verbose_name='Capacidad de aceite de diferencial')),
                ('fuel_filter_quantity', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cantidad de filtros de combustible')),
                ('fuel_part_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nomenclatura de filtro de combustible')),
                ('oil_filter_quantity', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cantidad de filtros de aceite')),
                ('oil_part_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nomenclatura de filtro de aceite')),
                ('air_filter_part_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nomenclatura de filtro de aire')),
                ('air_purifier_part_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nomenclatura de purificador de aire')),
                ('tire_size', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tamaño de neumático')),
                ('tire_brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca de neumático')),
                ('tire_pressure', models.CharField(blank=True, max_length=100, null=True, verbose_name='Presión de neumático')),
                ('brake_system_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de sistema de freno')),
                ('parking_brake_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de freno de estacionamiento')),
                ('pad_type', models.IntegerField(blank=True, choices=[(1, 'Orgánica'), (2, 'Semi-metálica'), (3, 'Metálica')], null=True, verbose_name='Tipo de pastilla')),
                ('disc_type', models.IntegerField(blank=True, choices=[(1, 'Sólido'), (2, 'Ventilado'), (3, 'Perforado')], null=True, verbose_name='Tipo de disco')),
                ('water_tank_capacity', models.CharField(blank=True, max_length=100, null=True, verbose_name='Capacidad de estanque de agua')),
                ('pump_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de bomba')),
                ('pump_capacity', models.CharField(blank=True, max_length=100, null=True, verbose_name='Capacidad de bomba')),
                ('pump_pressure', models.CharField(blank=True, max_length=100, null=True, verbose_name='Presión de bomba')),
                ('pump_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo de bomba')),
                ('pump_brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca de bomba')),
                ('pump_serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de serie de bomba')),
                ('pump_year', models.IntegerField(blank=True, null=True, verbose_name='Año de bomba')),
                ('maximum_flow_rate', models.CharField(blank=True, max_length=100, null=True, verbose_name='Caudal máximo')),
                ('registration_certificate', models.FileField(blank=True, null=True, upload_to='major_equipment/registration_certificates', verbose_name='Padrón del vehículo')),
                ('registration_certificate_expiration', models.DateField(blank=True, null=True, verbose_name='Vencimiento del padrón')),
                ('soap_certificate', models.FileField(blank=True, null=True, upload_to='major_equipment/soap_certificates', verbose_name='Certificado SOAP')),
                ('soap_certificate_expiration', models.DateField(blank=True, null=True, verbose_name='Vencimiento del SOAP')),
                ('technical_inspection_certificate', models.FileField(blank=True, null=True, upload_to='major_equipment/technical_inspection_certificates', verbose_name='Certificado de revisión técnica')),
                ('technical_inspection_certificate_expiration', models.DateField(blank=True, null=True, verbose_name='Vencimiento de la revisión técnica')),
                ('vehicle_permit', models.FileField(blank=True, null=True, upload_to='major_equipment/vehicle_permits', verbose_name='Permiso de circulación')),
                ('vehicle_permit_expiration', models.DateField(blank=True, null=True, verbose_name='Vencimiento del permiso de circulación')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Próxima mantención')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firebrigade.entity', verbose_name='Entidad asignada')),
                ('vehicle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='major_equipment.vehicletype', verbose_name='Tipo de vehículo')),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
                'permissions': [('view_company_majorequipment', 'Puede ver unidades de su compañía'), ('add_company_majorequipment', 'Puede agregar unidades para su compañía'), ('change_company_majorequipment', 'Puede modificar unidades de su compañía'), ('delete_company_majorequipment', 'Puede eliminar unidades de su compañía')],
            },
        ),
        migrations.CreateModel(
            name='UnitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='major_equipment/unit_images', verbose_name='Imagen')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='major_equipment.majorequipment', verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Imagen de unidad',
                'verbose_name_plural': 'Imágenes de unidades',
                'permissions': [('view_company_unitimage', 'Puede ver imágenes de unidades de su compañía'), ('add_company_unitimage', 'Puede agregar imágenes a unidades de su compañía'), ('change_company_unitimage', 'Puede modificar imágenes de unidades de su compañía'), ('delete_company_unitimage', 'Puede eliminar imágenes de unidades de su compañía')],
            },
        ),
    ]
