# Generated by Django 5.2 on 2025-04-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major_equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitimage',
            name='image',
            field=models.ImageField(upload_to='media/unit_images', verbose_name='Imagen'),
        ),
    ]
