# Generated by Django 5.2.4 on 2025-07-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major_equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuellog',
            name='cost',
            field=models.IntegerField(verbose_name='Costo (CLP)'),
        ),
    ]
