# Generated by Django 5.2 on 2025-07-08 17:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major_equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Etiqueta')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoría')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'permissions': [('view_company_majorequipment', 'Puede ver unidades de su compañía'), ('change_company_majorequipment', 'Puede modificar unidades de su compañía')], 'verbose_name': 'Unidad', 'verbose_name_plural': 'Unidades'},
        ),
        migrations.CreateModel(
            name='CheckListReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('completed', models.BooleanField(default=False, verbose_name='Completado')),
                ('editable', models.BooleanField(default=True, verbose_name='Editable')),
                ('deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('fuel_level', models.IntegerField(choices=[(0, 'Vacío'), (1, 'Un cuarto de tanque'), (2, 'Medio tanque'), (3, 'Tres cuartos de tanque'), (4, 'Tanque lleno')], default=0, verbose_name='Nivel de combustible')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_reports', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_reports', to='major_equipment.unit', verbose_name='Unidad')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255, verbose_name='Comentario')),
                ('status', models.IntegerField(choices=[(0, 'Sin responder'), (1, 'Bueno'), (2, 'Malo'), (3, 'No aplica')], default=0, verbose_name='Estado')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='check_entries', to='major_equipment.checklistreport', verbose_name='Reporte de checklist')),
                ('template_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='check_entries', to='major_equipment.checklisttemplateitem', verbose_name='Plantilla de checklist')),
            ],
        ),
    ]
