# Generated by Django 5.2 on 2025-07-11 01:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major_equipment', '0002_checklisttemplateitem_alter_unit_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistentry',
            options={'verbose_name': 'Entrada de checklist', 'verbose_name_plural': 'Entradas de checklist'},
        ),
        migrations.AlterModelOptions(
            name='checklisttemplateitem',
            options={'verbose_name': 'Ítem de plantilla', 'verbose_name_plural': 'Ítems de plantilla'},
        ),
        migrations.RemoveField(
            model_name='checklisttemplateitem',
            name='active',
        ),
        migrations.RemoveField(
            model_name='checklisttemplateitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='checklisttemplateitem',
            name='order',
        ),
        migrations.AddField(
            model_name='checklistentry',
            name='answer',
            field=models.CharField(default='', max_length=255, verbose_name='Respuesta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklistentry',
            name='question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='major_equipment.checklisttemplateitem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklisttemplateitem',
            name='question_type',
            field=models.CharField(choices=[('YN', 'Sí o No'), ('MC', 'Opciones predefinidas'), ('TX', 'Descriptivo')], default='YN', max_length=2, verbose_name='Tipo de pregunta'),
        ),
        migrations.AlterField(
            model_name='checklistentry',
            name='comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Comentario adicional'),
        ),
        migrations.CreateModel(
            name='ChecklistOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Opción')),
                ('question', models.ForeignKey(limit_choices_to={'question_type': 'MC'}, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='major_equipment.checklisttemplateitem', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Opción de plantilla',
                'verbose_name_plural': 'Opciones de plantilla',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha del reporte')),
                ('editable', models.BooleanField(default=True, verbose_name='Editable')),
                ('deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_reports', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_reports', to='major_equipment.unit', verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-date'],
                'unique_together': {('unit', 'date')},
            },
        ),
        migrations.AlterField(
            model_name='checklistentry',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='major_equipment.report'),
        ),
        migrations.AlterUniqueTogether(
            name='checklistentry',
            unique_together={('report', 'question')},
        ),
        migrations.DeleteModel(
            name='CheckListReport',
        ),
        migrations.RemoveField(
            model_name='checklistentry',
            name='status',
        ),
        migrations.RemoveField(
            model_name='checklistentry',
            name='template_item',
        ),
    ]
