# Generated by Django 5.2 on 2025-04-11 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major_equipment', '0002_alter_unitimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descripción del desperfecto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reporte')),
                ('editable', models.BooleanField(default=True, verbose_name='Editable')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Reportado por')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='major_equipment.majorequipment', verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Reporte de desperfecto',
                'verbose_name_plural': 'Reportes de desperfectos',
                'permissions': (('create_company_maintenancereports', 'Puede crear reportes de su compañía'), ('view_company_maintenancereports', 'Puede ver reportes de su compañía'), ('change_company_maintenancereports', 'Puede editar reportes de su compañía'), ('delete_company_maintenancereports', 'Puede eliminar reportes de su compañía'), ('create_own_maintenancereports', 'Puede crear sus propios reportes'), ('view_own_maintenancereports', 'Puede ver sus propios reportes'), ('change_own_maintenancereports', 'Puede editar sus propios reportes'), ('delete_own_maintenancereports', 'Puede eliminar sus propios reportes')),
            },
        ),
    ]
