# Generated by Django 5.2 on 2025-07-11 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major_equipment', '0003_alter_checklistentry_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Etiqueta')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.AlterField(
            model_name='checklistentry',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='major_equipment.report', verbose_name='Reporte'),
        ),
        migrations.CreateModel(
            name='ReportTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Etiqueta')),
                ('question_type', models.IntegerField(choices=[(1, 'Sí o No'), (2, 'Opciones predefinidas'), (3, 'Descriptivo')], default=3, verbose_name='Tipo de pregunta')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='major_equipment.itemcategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Ítem de plantilla',
                'verbose_name_plural': 'Ítems de plantilla',
            },
        ),
        migrations.CreateModel(
            name='ReportItemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Opción')),
                ('question', models.ForeignKey(limit_choices_to={'question_type': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='major_equipment.reporttemplateitem', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Opción de plantilla',
                'verbose_name_plural': 'Opciones de plantilla',
            },
        ),
        migrations.AlterField(
            model_name='checklistentry',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='major_equipment.reporttemplateitem', verbose_name='Pregunta'),
        ),
        migrations.DeleteModel(
            name='ChecklistOption',
        ),
        migrations.DeleteModel(
            name='ChecklistTemplateItem',
        ),
    ]
