# Generated by Django 5.2.4 on 2025-07-31 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major_equipment', '0004_alter_maintenancelog_admin_reviewed_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='state',
            field=models.IntegerField(choices=[(1, 'Bueno'), (2, 'En mantención')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='reviewed_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_logs_reviewed_admin', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por (Administración)'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='reviewed_by_command',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_logs_reviewed_command', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por (Comandancia)'),
        ),
    ]
