# Generated by Django 5.2 on 2025-07-11 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('major_equipment', '0004_itemcategory_alter_checklistentry_report_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChecklistEntry',
            new_name='ReportEntry',
        ),
    ]
