# Generated by Django 5.2 on 2025-04-13 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('major_equipment', '0005_delete_workshop_alter_maintenancereport_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancereport',
            options={'permissions': (('view_own_maintenancereports', 'Puede ver sus propios reportes de mantención'), ('change_own_maintenancereports', 'Puede editar sus propios reportes de mantención'), ('delete_own_maintenancereports', 'Puede eliminar sus propios reportes de mantención'), ('view_company_maintenancereports', 'Puede ver reportes de su compañía'), ('create_company_maintenancereports', 'Puede crear reportes en su compañía'), ('change_company_maintenancereports', 'Puede editar reportes de su compañía'), ('delete_company_maintenancereports', 'Puede eliminar reportes de su compañía'), ('create_body_maintenancereports', 'Puede crear reportes en cualquier entidad'), ('change_body_maintenancereports', 'Puede editar reportes de cualquier entidad'), ('delete_body_maintenancereports', 'Puede eliminar reportes de cualquier entidad')), 'verbose_name': 'Reporte de desperfecto', 'verbose_name_plural': 'Reportes de desperfectos'},
        ),
    ]
