# Generated by Django 5.2 on 2025-07-12 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major_equipment', '0005_rename_checklistentry_reportentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='coment',
            field=models.TextField(blank=True, null=True, verbose_name='Comentario'),
        ),
    ]
