# Generated by Django 5.2 on 2025-04-13 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('major_equipment', '0006_alter_maintenancereport_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitimage',
            options={'verbose_name': 'Imagen de unidad', 'verbose_name_plural': 'Imágenes de unidades'},
        ),
    ]
