# Generated by Django 4.2.7 on 2025-08-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major_equipment', '0006_alter_unit_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplateitem',
            name='units',
            field=models.ManyToManyField(blank=True, help_text='Selecciona las unidades en las que esta pregunta debe aparecer. Si no seleccionas ninguna, la pregunta no se usará.', related_name='report_template_items', to='major_equipment.unit', verbose_name='Unidades asignadas'),
        ),
    ]
