# Generated by Django 4.2.7 on 2025-08-05 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('major_equipment', '0007_reporttemplateitem_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportitemoption',
            name='triggers_alert',
            field=models.BooleanField(default=False, verbose_name='Activar alerta'),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='label',
            field=models.CharField(max_length=255, unique=True, verbose_name='Etiqueta'),
        ),
        migrations.AlterField(
            model_name='reporttemplateitem',
            name='question_type',
            field=models.IntegerField(choices=[(1, 'Bueno/Malo'), (2, 'Opciones predefinidas'), (3, 'Numérico')], default=1, verbose_name='Tipo de pregunta'),
        ),
        migrations.CreateModel(
            name='NumericAlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.IntegerField(blank=True, null=True, verbose_name='Valor mínimo (opcional)')),
                ('max_value', models.IntegerField(blank=True, null=True, verbose_name='Valor máximo (opcional)')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción de la alerta')),
                ('question', models.ForeignKey(limit_choices_to={'question_type': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='numeric_alert_rules', to='major_equipment.reporttemplateitem', verbose_name='Pregunta numérica')),
            ],
            options={
                'verbose_name': 'Regla para alerta numérica',
                'verbose_name_plural': 'Reglas para alerta numéricas',
            },
        ),
    ]
